import { http } from '@/api/http';

/**
* @link http://47.108.139.107:16700/doc.html#/default/导出相关/generateTicketUsingPOST
*/
export default function fetchMethod(options: { params: { enterpriseCode?: string; enterpriseId?: number; searchJson?: string; type?: Etype; userId?: number } }, extraOptions?: any) {
    return http<IJSONResultExportedTicketInformation>(
        {
            url: "/masterdata-service/exportAuth/generateTicket",
            method: "post",
            ...options,
        },
        extraOptions,
    );
}
/** JSONResult«导出ticket信息» */
export interface IJSONResultExportedTicketInformation {
    /** 返回码 */
    code?: number;
    /** 返回消息说明 */
    msg?: string;
    /** 响应结果 */
    data?: IExportingTicketInformation;
    /** 服务器结果返回时的 Unix timestamp,单位毫秒 */
    ts?: number;
}
/** 导出ticket信息 */
export interface IExportingTicketInformation {
    /** 导出凭证ticket */
    ticket?: string;
}

export enum Etype {
    USER = "USER",
    MAJOR_DATA = "MAJOR_DATA",
    BOM = "BOM",
    DEVICE = "DEVICE",
    DEVICE_COLLECTION_PARAM = "DEVICE_COLLECTION_PARAM",
    PROCESS = "PROCESS",
    WORK_PLACE = "WORK_PLACE",
    MAJOR_DATA_UNIT = "MAJOR_DATA_UNIT",
    PRODUCE_TAG = "PRODUCE_TAG",
    PRODUCE_ABNORMAL_CATEGORY = "PRODUCE_ABNORMAL_CATEGORY",
    ROUTING = "ROUTING",
    PRODUCE_ROUTING = "PRODUCE_ROUTING",
    PRODUCE_ROUTING_FAST = "PRODUCE_ROUTING_FAST",
    SUPPLIER = "SUPPLIER",
    CUSTOMER = "CUSTOMER",
    ANDON_STATION_MACHINE = "ANDON_STATION_MACHINE",
    PRODUCE_ENTRUST = "PRODUCE_ENTRUST",
    DEVICE_COLLECTION_STATISTIC = "DEVICE_COLLECTION_STATISTIC",
    DEVICE_COLLECTION_DETAIL = "DEVICE_COLLECTION_DETAIL",
    WAREHOUSE = "WAREHOUSE",
    USER_REPORT = "USER_REPORT",
    SALES_ORDER_REPORT = "SALES_ORDER_REPORT",
    PRODUCTION_REPORT_CLASS_GROUP = "PRODUCTION_REPORT_CLASS_GROUP",
    PRODUCTION_REPORT_PROCESS = "PRODUCTION_REPORT_PROCESS",
    PRODUCTION_REPORT_MAJOR_DATA = "PRODUCTION_REPORT_MAJOR_DATA",
    PRODUCTION_REPORT_DATA = "PRODUCTION_REPORT_DATA",
    PRODUCE_TIME_FEE_DETAIL = "PRODUCE_TIME_FEE_DETAIL",
    PRODUCE_TIME_FEE_MONTH = "PRODUCE_TIME_FEE_MONTH",
    YIELD_RATE_REPORT_CLASS_GROUP = "YIELD_RATE_REPORT_CLASS_GROUP",
    SCRAP_REPORT_CLASS_GROUP = "SCRAP_REPORT_CLASS_GROUP",
    SCRAP_REPORT_PROCESS = "SCRAP_REPORT_PROCESS",
    SCRAP_REPORT_MAJOR_DATA = "SCRAP_REPORT_MAJOR_DATA",
    SCRAP_REPORT_TYPE = "SCRAP_REPORT_TYPE",
    SCRAP_REPORT_DATA = "SCRAP_REPORT_DATA",
    PRODUCE_FEE_REPORT = "PRODUCE_FEE_REPORT",
    PRODUCE_ENTRUST_REPORT = "PRODUCE_ENTRUST_REPORT",
    FPY_RATE_REPORT_DATA = "FPY_RATE_REPORT_DATA",
    FPY_RATE_REPORT = "FPY_RATE_REPORT",
    WIP_REPORT = "WIP_REPORT",
    WIP_EXCEPTION_REPORT = "WIP_EXCEPTION_REPORT",
    ANDON_CALL_ANALYZE_REPORT = "ANDON_CALL_ANALYZE_REPORT",
    ANDON_DEVICE_FAULT_REPORT = "ANDON_DEVICE_FAULT_REPORT",
    ANDON_BAD_INCOMING_REPORT = "ANDON_BAD_INCOMING_REPORT",
    ANDON_ABNORMAL_QUALITY_REPORT = "ANDON_ABNORMAL_QUALITY_REPORT",
    XINDE_COATING_LINE_DAILY_REPORT = "XINDE_COATING_LINE_DAILY_REPORT",
    XINDE_DZJ_STATISTIC_REPORT = "XINDE_DZJ_STATISTIC_REPORT",
    XINDE_FBJ_STATISTIC_REPORT = "XINDE_FBJ_STATISTIC_REPORT",
    XINDE_GZX_STATISTIC_REPORT = "XINDE_GZX_STATISTIC_REPORT",
    BAO_JING_SALES_DELIVER_REPORT = "BAO_JING_SALES_DELIVER_REPORT",
    BAO_JING_CONSIGNMENT_INBOUND_ANALYZE_REPORT = "BAO_JING_CONSIGNMENT_INBOUND_ANALYZE_REPORT",
    BAO_JING_CONSIGNMENT_LOSS_ANALYZE_REPORT = "BAO_JING_CONSIGNMENT_LOSS_ANALYZE_REPORT",
    BAO_JING_ACCOUNTS_RECEIVABLE_REPORT = "BAO_JING_ACCOUNTS_RECEIVABLE_REPORT",
    BAO_JING_COLLECTION_TOTAL_REPORT = "BAO_JING_COLLECTION_TOTAL_REPORT",
    BAO_JING_PURCHASE_ARRIVED_STATISTIC_REPORT = "BAO_JING_PURCHASE_ARRIVED_STATISTIC_REPORT",
    BAO_JING_AFTER_SALES_QUALITY_REPORT = "BAO_JING_AFTER_SALES_QUALITY_REPORT",
    BAO_JING_PRODUCE_STORAGE_REPORT = "BAO_JING_PRODUCE_STORAGE_REPORT",
    BAO_JING_RAW_STORAGE_REPORT = "BAO_JING_RAW_STORAGE_REPORT",
    BAO_JING_SCRAP_REPORT = "BAO_JING_SCRAP_REPORT",
    QUALITY_GOOD_SCRAP_REPORT = "QUALITY_GOOD_SCRAP_REPORT",
    STORAGE_TAKE_CHECK_TASK_DETAIL = "STORAGE_TAKE_CHECK_TASK_DETAIL",
    STORAGE_TAKE_CHECK_TASK_DETAIL_LOT = "STORAGE_TAKE_CHECK_TASK_DETAIL_LOT",
    STORAGE_TAKE_CHECK_TASK_DETAIL_SERIAL_NO = "STORAGE_TAKE_CHECK_TASK_DETAIL_SERIAL_NO",
    STORAGE_TAKE_CHECK_TASK_DETAIL_LOT_SERIAL_NO = "STORAGE_TAKE_CHECK_TASK_DETAIL_LOT_SERIAL_NO",
    PROJECT_TASK_EXPORT = "PROJECT_TASK_EXPORT",
    PROJECT_TASK_IMPORT = "PROJECT_TASK_IMPORT",
    QMS_QUALITY_MONTH_REPORT_EXPORT = "QMS_QUALITY_MONTH_REPORT_EXPORT",
    QMS_QUALITY_MONTH_REPORT_DEPARTMENT_EXPORT = "QMS_QUALITY_MONTH_REPORT_DEPARTMENT_EXPORT"
}
